### ISSUE TITLE
Runtime error while running test  for wrapping error elements with div element

### ISSUE THREAD

**Issue by shan9101** [techvision/waiable#31]
We are getting runtime error while executing test for wrapping error elements with the div element.
test case in form_helper_test.rb:
test "wrap error element with div element" do
    include ActiveModel
    expect = '<div id="error_user_first_name"></div>'.html_safe
    form_buffer = form_for :person, url: "dummy" do |f|
      :person.errors.full_messages.each do |msg|
        actual = '<li>msg</li>'.html_safe
        assert_match(expect, actual)
      end
    end    
  end
Test_helper.rb:

require 'minitest/autorun'
require 'minitest/unit'
require 'minitest/spec'
require 'minitest/pride'
#require 'xmlsimple'
require 'active_model'
require 'action_view'
require 'action_view/test_case'

require 'support/person'

require 'waiable'

On runningtest getting the following error message:
 
 15) Error:
WaiableFormBuilderTest#test_wrap_error_element_with_div_element:
RuntimeError: In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers`.
    /home/shantanu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/url_for.rb:13:in `_routes'
    /home/shantanu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/test_case.rb:267:in `method_missing'
    /home/shantanu/Techvision/waiable/test/action_view/helpers/form_helper_test.rb:206:in `block in <class:WaiableFormBuilderTest>'

**Comment by narutosanjiv** [comment]
@shan9101  What is status of this issue?

**Comment by Sanghapal** [comment]
@narutosanjiv  Not resolve yet.

**Comment by narutosanjiv** [comment]
@Sanghapal  Are you facing  this issue only when you running 'rake test'?

**Comment by shan9101** [comment]
Getting this error only for this test case on running rake test. Other test cases are running successfully.

**Comment by anilmaurya** [comment]
@shan9101 Error message is misleading .

Error is raised by line :
expect = assert_raises(ArgumentError) {image_tag("techvision.png") if alt == ""}

you have used `alt` variable which is not defined.

Defining `alt` before assertion will fix this Issue.

**Comment by shan9101** [comment]
We are getting error for this test case: (form_helper_test.rb)
  test "wrap error element with div element" do
    include ActiveModel
    expect = '<' 'div id="error_user_first_name"><'/div>'.html_safe
    form_buffer = form_for :person, url: "dummy" do |f|
      :person.errors.full_messages.each do |msg|
        actual = '<' li>msg</li>'.html_safe
        assert_match(expect, actual)
      end
    end    
You are referring to another test case.That test case failed but there is no error.

**Comment by anilmaurya** [comment]
@shan9101 

Replace your test case with :
```
   test "wrap error element with div element" do
       person = Person.new
       expect = '<div id="error_user_first_name"></div>'.html_safe
       form_buffer = form_for person, url: "dummy", as: 'person_form' do |f| 
         f.object.errors.full_messages.each do |msg|
           actual = '<li>msg</li>'.html_safe
           assert_match(expect, actual)
         end
       end      
     end 

```

**Comment by shan9101** [comment]
This issue is fixed. We are not getting this error message. thanks Anil.
Closing this issue.

**Comment by shan9101** [comment]
We are getting the same error message as URL routing helper need to be included to run this test case.
Re opening this issue.

**Comment by anilmaurya** [comment]
@shan9101 can you update repo with latest code and I will check locally.

**Comment by shan9101** [comment]
Updated repo with latest test case.

**Comment by anilmaurya** [comment]
@shan9101 I can see

```
 15) Failure:
WaiableAssetUrlTest#test_testing_image_tag_with_alt_attribute [/home/anil/work/opensource/waiable/test/action_view/helpers/assert_tag_helper_test.rb:3]:
[ArgumentError] exception expected, not
Class: <RuntimeError>
Message: <"In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers`.">
```

I already mentioned steps to solve this error by defining alt variable.

If you are facing some other issue, then let me know.

**Comment by shan9101** [comment]
This issue is fixed.
