### ISSUE TITLE
Error while running application rails 5

### ISSUE THREAD

**Issue by shan9101** [techvision/waiable#35]
I am trying to run simple blog application with rails 5 development version.We will add our waiable gem features into rails 5 forked repo. But on running bundle install, I am getting following error message:

Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Bundler could not find compatible versions for gem "arel":
  In Gemfile:
    rails (>= 0) ruby depends on
      activerecord (= 5.0.0.alpha) ruby depends on
        arel (= 7.0.0.alpha) ruby
Could not find gem 'arel (= 7.0.0.alpha) ruby', which is required by gem
'activerecord (= 5.0.0.alpha) ruby', in any of the sources.

**Comment by anilmaurya** [comment]
Can you mention steps to reproduce this error ?

**Comment by shan9101** [comment]
I have cloned the rails 5 repo, created branch waiable_5. Then added this to blog app's gem file:
gem 'rails', path: '/home/shantanu/Techvision/rails', branch: 'waiable_5'

Then on running bundle install encountered the error.

**Comment by anilmaurya** [comment]
There is a issue related to this error 

https://github.com/rails/rails/issues/19624

To solve this , add `gem 'arel', github: 'rails/arel'` to your Gemfile

**Comment by shan9101** [comment]
Thanks Anil ! this error got resolved..
